# Generated by Django 2.2.8 on 2020-02-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200123_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image_filter', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=250)),
                ('opacity', models.CharField(max_length=5)),
                ('blend_mode', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter', to='system.Filter'),
        ),
    ]
