# Generated by Django 2.2.8 on 2019-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('AFF', 'Affiliate'), ('CUS', 'Customer')], default='CUS', max_length=5),
        ),
    ]
