# Generated by Django 2.2.8 on 2019-12-29 20:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191229_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='inviteuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='note',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='sponsor',
            field=models.CharField(default='0', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sponsor',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
