# Generated by Django 2.2.8 on 2019-12-30 05:38

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import invites.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user_photos')),
                ('note', models.TextField(blank=True, max_length=250)),
                ('sponsor', models.UUIDField()),
                ('expiration', models.DateTimeField(default=invites.models.invitation_expiration)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
